#!/usr/bin/env python3
"""Extract only normative data from pinned RFC 7932, not an upstream decoder."""

import argparse
import ast
import base64
import hashlib
import json
import re
import urllib.request
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DICTIONARY = ROOT / 'assets/data/brotli-dictionary.bin'
TABLES = ROOT / 'js/lib/archive/brotli-tables.js'


def validate_local(dictionary=DICTIONARY, tables=TABLES):
  # Fixed normative tables are verified offline on every PR; a new RFC snapshot
  # never regenerates or changes these pins automatically.
  for path, expected in [
    (dictionary, '20e42eb1b511c21806d4d227d07e5dd06877d8ce7b3a817f378f313653f35c70'),
    (tables, '7e347bf611214e01751e1f1366d3b40b59d2d9b2ec3152bace33f95c23419b44'),
  ]:
    if hashlib.sha256(path.read_bytes()).hexdigest() != expected:
      raise ValueError(f'{path.name}: RFC 7932 normative asset integrity mismatch')


def checked(data, length, crc):
  if len(data) != length or zlib.crc32(data) != crc:
    raise ValueError('RFC 7932 normative data length/CRC mismatch')
  return data


def extract(source):
  pin = json.loads((ROOT / 'scripts/compression-spec-lock.json').read_text())['rfcs']['7932']
  if 'sha384-' + base64.b64encode(hashlib.sha384(source).digest()).decode() != pin['sha384']:
    raise ValueError('RFC 7932 source integrity mismatch')
  text = source.decode('ascii')
  appendix = text.split('Appendix A.  Static Dictionary Data\n')[1].split('Appendix B.')[0]
  dictionary = checked(bytes.fromhex(''.join(re.findall(r'^      ([0-9a-f]+)$', appendix, re.M))),
                       122784, 0x5136cb04)
  arrays = []
  for name, crc in [('Lut0', 0x8e91efb7), ('Lut1', 0xd01a32f4), ('Lut2', 0x0dd7a0d6)]:
    section = text.split(name + ' :=\n')[1].split('\n\n')[0]
    arrays.append((name.upper(), checked(bytes(map(int, re.findall(r'\d+', section))), 256, crc)))
  nd = text.split('NDBITS :=')[1].split('\n\n')[0]
  arrays.append(('DICTIONARY_BITS', bytes(map(int, re.findall(r'\d+', nd)))))
  transforms, serialized = [], bytearray()
  pattern = r'^\s+(\d+)\s+("(?:\\.|[^"\\])*")\s+(\w+)\s+("(?:\\.|[^"\\])*")\s*$'
  for row in re.finditer(pattern, text.split('Appendix B.  List of Word Transformations\n')[1], re.M):
    index, prefix, operation, suffix = row.groups()
    if int(index) != len(transforms):
      raise ValueError('RFC 7932 transform order mismatch')
    prefix, suffix = ast.literal_eval(prefix), ast.literal_eval(suffix)
    opcode = {'Identity': 0, 'FermentFirst': 1, 'FermentAll': 2}.get(operation)
    if opcode is None:
      opcode = int(re.search(r'\d+', operation)[0]) + (2 if operation.startswith('OmitFirst') else 11)
    transforms.append([prefix, opcode, suffix])
    serialized.extend(prefix.encode('latin1') + bytes([0, opcode]) + suffix.encode('latin1') + b'\0')
  checked(serialized, 648, 0x3d965f81)
  if len(transforms) != 121 or len(arrays[-1][1]) != 25:
    raise ValueError('RFC 7932 table count mismatch')
  lines = [
    '// Generated by scripts/generate_brotli_data.py from RFC 7932 sections 7.1, A and B.',
    '// Copyright (c) 2016 IETF Trust and the persons identified as the document authors.',
    '// All rights reserved. Subject to the Revised BSD License in THIRD_PARTY_NOTICES.md.',
    '// No decoder implementation is included in this generated normative data.',
    '',
  ]
  for name, data in arrays:
    lines.append(f'export const {name} = new Uint8Array([')
    lines.extend('  ' + ', '.join(map(str, data[i:i + 16])) + ',' for i in range(0, len(data), 16))
    lines.append(']);\n')
  lines.append('export const TRANSFORMS = [')
  for prefix, opcode, suffix in transforms:
    # C strings are byte strings; the JS decoder reads code units, not UTF-8.
    def quote(value):
      return "'" + json.dumps(value, ensure_ascii=True)[1:-1].replace('\\"', '"').replace("'", "\\'") + "'"
    lines.append(f'  [{quote(prefix)}, {opcode}, {quote(suffix)}],')
  lines.append('];\n')
  return dictionary, '\n'.join(lines).encode()


def main():
  parser = argparse.ArgumentParser(description=__doc__)
  parser.add_argument('--source', type=Path, help='Use a downloaded RFC instead of the official URL.')
  parser.add_argument('--check', action='store_true', help='Compare generated files without writing.')
  args = parser.parse_args()
  if args.source:
    source = args.source.read_bytes()
  else:
    with urllib.request.urlopen('https://www.rfc-editor.org/rfc/rfc7932.txt', timeout=30) as response:
      source = response.read()
  for path, data in zip((DICTIONARY, TABLES), extract(source)):
    if args.check:
      if path.read_bytes() != data:
        raise ValueError(f'{path.relative_to(ROOT)} differs from RFC 7932')
    else:
      path.write_bytes(data)
    print(f'{path.relative_to(ROOT)}: {len(data)} bytes, SHA-256 {hashlib.sha256(data).hexdigest()}')
  validate_local()


if __name__ == '__main__':
  main()
